### ISSUE TITLE
Implement missing Rserve XT_ types

### ISSUE THREAD

**Issue by cubranic** [cubranic/Statistics-R-IO#1]
- [x] ~~#49: XT_S4~~
- [x] ~~#29~~: XT_CLOS
- [x] ~~#47~~: XT_LIST_NOTAG    data: same as XT_VECTOR
- [x] ~~#26~~: XT_VECTOR_EXP   data: same as XT_VECTOR (EXPSXP)``
- [x] ~~#30~~: XT_ARRAY_CPLX    data: (n*16) double(re),double(im),..
